In [38]:
import torch
from torch import nn
from torch.nn import init
import numpy as np
import sys
sys.path.append("D:\CS\MachineLearning\Dive-into-DL-PyTorch-master\code") # 为了导入上层目录的d2lzh_pytorch
import d2lzh_pytorch as d2l

In [39]:
num_inputs=784
num_outputs=10

batch_size = 256
train_iter, test_iter=d2l.load_data_fashion_mnist(batch_size)

'''class LinearNet(nn.Module):
    def __init__(self,num_inputs,num_outputs):
        super(LinearNet,self).__init__()
        self.Linear=nn.Linear(num_inputs,num_outputs)
    def forward(self,x):
        y=self.Linear(x.view(x.shape[0],-1))
        return y
net=LinearNet(num_inputs,num_outputs)'''

'class LinearNet(nn.Module):\n    def __init__(self,num_inputs,num_outputs):\n        super(LinearNet,self).__init__()\n        self.Linear=nn.Linear(num_inputs,num_outputs)\n    def forward(self,x):\n        y=self.Linear(x.view(x.shape[0],-1))\n        return y\nnet=LinearNet(num_inputs,num_outputs)'

In [40]:
class FlattenLayer(nn.Module):
    def __init__(self):
        super(FlattenLayer, self).__init__()
    def forward(self,x): # x shape: (batch, *, *, ...)
        return x.view(x.shape[0],-1)

In [41]:
from collections import OrderedDict

net = nn.Sequential(
    # FlattenLayer(),
    # nn.Linear(num_inputs, num_outputs)
    OrderedDict([
        ('flatten', FlattenLayer()),
        ('linear', nn.Linear(num_inputs, num_outputs))
    ])
)
print(net)

Sequential(
  (flatten): FlattenLayer()
  (linear): Linear(in_features=784, out_features=10, bias=True)
)


In [42]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.0221,  0.0029, -0.0267,  ..., -0.0221, -0.0153, -0.0083],
        [ 0.0126, -0.0072,  0.0337,  ...,  0.0310, -0.0351, -0.0034],
        [-0.0160,  0.0065,  0.0255,  ...,  0.0190, -0.0106,  0.0162],
        ...,
        [-0.0271,  0.0342,  0.0320,  ...,  0.0270, -0.0152,  0.0316],
        [ 0.0185,  0.0214, -0.0094,  ..., -0.0167, -0.0096, -0.0194],
        [ 0.0131, -0.0007, -0.0142,  ..., -0.0015,  0.0023, -0.0133]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0289,  0.0226, -0.0097,  0.0292,  0.0284, -0.0183, -0.0173,  0.0138,
        -0.0226, -0.0137], requires_grad=True)


In [43]:
init.normal_(net[1].weight,mean=0,std=0.01)
init.constant_(net[1].bias,val=0)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [44]:
loss=nn.CrossEntropyLoss()

In [45]:
optimizer=torch.optim.SGD(net.parameters(),lr=0.1)

In [46]:
num_epochs=5
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, optimizer)

epoch 1, loss 0.0031, train acc 0.749, test acc 0.790
epoch 2, loss 0.0022, train acc 0.812, test acc 0.800
epoch 3, loss 0.0021, train acc 0.826, test acc 0.797
epoch 4, loss 0.0020, train acc 0.833, test acc 0.821
epoch 5, loss 0.0019, train acc 0.837, test acc 0.820
