In [2]:
import torch
import matplotlib as plot
import numpy as np
import torchvision
import sys
sys.path.append("D:\CS\MachineLearning\Dive-into-DL-PyTorch-master\code") # 为了导入上层目录的d2lzh_pytorch
import d2lzh_pytorch as d2l

In [3]:
batch_size=256
train_iter,test_iter=d2l.load_data_fashion_mnist(batch_size)

In [5]:
num_inputs=784
num_outputs=10
W=torch.tensor(np.random.normal(0,0.01,(num_inputs,num_outputs)),dtype=torch.float,requires_grad=True)
b=torch.zeros(num_outputs,dtype=torch.float,requires_grad=True)

In [11]:
X=torch.tensor([[1,2,3],[2,3,5]])
print(X.sum(dim=0,keepdim=True))
print(X.sum(dim=1,keepdim=True))

tensor([[3, 5, 8]])
tensor([[ 6],
        [10]])


In [14]:
def softmax(X):
    X_exp=X.exp()
    total=X_exp.sum(dim=1,keepdim=True)
    return X_exp/total

In [15]:
X = torch.rand((2, 5))
X_prob = softmax(X)
print(X_prob, X_prob.sum(dim=1))

tensor([[0.2558, 0.1794, 0.1979, 0.1730, 0.1940],
        [0.2152, 0.2421, 0.1274, 0.1483, 0.2670]]) tensor([1., 1.])


In [17]:
def net(X):
    return torch.mm(X.view((-1,nums_inputs)),W)+b