In [11]:
import numpy as np
import torch
import random
import torch.utils.data as Data
import torch.nn as nn

In [12]:
num_examples=1000
num_inputs=2
true_w=[2,-3.4]
true_b=4.2
features=torch.tensor(np.random.normal(0,1,(num_examples,num_inputs)),dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [13]:
batch_size=10
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)

In [21]:
for X,y in data_iter:
    print(X,y)
    break

tensor([[ 0.1163,  2.1582],
        [ 0.0269, -1.4639],
        [ 0.6994, -0.6214],
        [-1.6350,  1.7851],
        [ 0.9358,  0.6801],
        [-0.4751,  0.1174],
        [-0.2892, -1.3047],
        [ 1.2772, -0.1372],
        [ 0.6582, -2.1242],
        [-0.0550,  0.3448]]) tensor([-2.9104,  9.2329,  7.7157, -5.1463,  3.7565,  2.8543,  8.0762,  7.2244,
        12.7407,  2.9306])


In [26]:
class LinearNet(nn.Module):
    def __init__(self,n_feature):
        super(LinearNet, self).__init__()
        self.linear=nn.Linear(n_feature,1)
    def forward(self,x):
        y=self.linear(x)
        return y
net=LinearNet(num_inputs)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [28]:
net=nn.Sequential(
    nn.Linear(num_inputs,1)
)
print(net)
print(net[0])

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [29]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.6568, -0.3097]], requires_grad=True)
Parameter containing:
tensor([-0.3022], requires_grad=True)


In [30]:
#初始化参数
from torch.nn import init

init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [31]:
#定义损失函数
loss=nn.MSELoss()

In [32]:
#确定优化算法
import torch.optim as optim
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [33]:
#训练模型
num_epochs=3
for epoch in range(1,num_epochs+1):
    for X,y in data_iter:
        output=net(X)
        l=loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch:%d,loss:%f'%(epoch,l.item()))

epoch:1,loss:0.000324
epoch:2,loss:0.000182
epoch:3,loss:0.000096


In [34]:
print(true_w,net[0].weight)
print(true_b,net[0].bias)

[2, -3.4] Parameter containing:
tensor([[ 2.0007, -3.4000]], requires_grad=True)
4.2 Parameter containing:
tensor([4.1992], requires_grad=True)
